services:
  - type: web
    name: sinergiia-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_TOKEN
        sync: false